name: Build Recipe Website

on:
  push:
    branches:
      - "master"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Recipe Grid
      run: |
        python -m pip install "recipe_grid>=2.0,<3.0"
    - uses: actions/checkout@v2
    - name: Build site
      run: |
        recipe-grid-site recipes out
    - name: Publish to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out
        cname: recipes.18sg.net
